### ISSUE TITLE
Object comparison of different types

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1009]
# Feature Request

Currently if you have different objects in list i.e. `InstrumentId`, `BarType` etc and try to match by index it will raise runtime error. I think returning `False` for simply no match shall suffice?

```
TypeError: Argument 'other' has incorrect type (expected nautilus_trader.model.data.bar.Bar, got nautilus_trader.model.identifiers.InstrumentId)
```

**Comment by cjdsellers** [comment]
This is interesting, could you clarify what you mean a little more by _"match by index"_?

The intent of this strict equality limitation was to enforce some correctness, so you wouldn't have a situation where you had mixed types in a list (your situation above). This is similar to what would happen in statically typed languages, such as Rust - if you didn't define some custom trait, you could only have `Vec<InstrumentId>` and `Vec<BarType>` so the compiler knows exactly what to expect when iterating over the vec etc.

Having said that, your suggestion certainly is more 'pythonic', but certain design decisions were made influenced by the fact so much code flows through Cython/Rust in more strongly typed contexts (and increasingly so). So generally when it comes to core types, the behavior tends to be stricter than more idiomatic/dynamic Python.

This is also very applicable to the identifiers, where `instrument_id == order_id` equality is immediately an error, rather than returning an ambiguous `False`.

**Comment by cjdsellers** [comment]
What exactly is the use case for having `InstrumentId` and `BarType` in the same list? Could it be possible to refactor the code to use dicts instead in some way?

**Comment by rsmb7z** [comment]
In the IB client, I am maintaining two seperate classes for `datarequests` and `subscriptions`, so I was storing the BarType and InstrumentId as identifer which servers as a lookup style betwen Nautilus and the RequestId/SubscriptionId from the client. During lookup iteration I ended up with this error while Python other objects were iterating in mix and match scneario. I have now used it as string of InstrumentId/BarType.
I agree about the mixing and type safety should be priority, so we can keep it like this - you are expert on the topic. Just courious though it wouldn't match anyway or there are some chances of matching if hard check on class type is not enforced?

**Comment by cjdsellers** [comment]
So in your case, this is approximately the code in question (it looks like you were comparing `Bar` to `InstrumentId` by the way):
```cython
    def __eq__(self, BarType other) -> bool:
        return bar_type_eq(&self._mem, &other._mem)
```

So `other` is defined as a `BarType` and Cython will generate C code which will check the type of `other` and raise this Python `TypeError` if any type other than `BarType` is passed to `__eq__` here.

You can see that this is important, because `other` is then passed across the C API into Rust.

You're correct that two objects of different types are very unlikely to match as strings (not impossible), but this is just a much earlier enforcement of correctness, with the design premise that only objects of the same type should be involved in equality checks or comparisons.

Closing this as I believe we're on the same page. Please continue to provide your thoughts though as different perspectives are extremely valuable, and we're likely to reach better designs and APIs if assumptions and legacy decisions are challenged like this.

**Comment by rsmb7z** [comment]
Yes understood.
