### ISSUE TITLE
`ts_event` was greater than `ts_init`

### ISSUE THREAD

**Issue by OnlyC** [nautechsystems/nautilus_trader#1014]
# Bug Report
![image](https://user-images.githubusercontent.com/1250580/219857552-2387ca81-5de0-4c55-b434-ad843104f10d.png)

When running `request_trade_ticks()` for historical ticks, new live tick from exchange still coming in creating those errors.

### Expected Behavior
Have a flag that historical data processing is done or not yet done before processing new data.

### Steps to Reproduce the Problem
```python
now = datetime.now(timezone.utc)
yesterday = now - timedelta(days=1)
from_datetime = pd.Timestamp(yesterday)
self.request_trade_ticks(
    instrument_id=self.instrument_id,
    from_datetime=from_datetime,
    to_datetime=pd.Timestamp(now),
)
```

### Specifications

- Python version: 3.10.5
- `nautilus_trader` version: 1.169.0 (develop built)

**Comment by cjdsellers** [comment]
So my understanding from your description and the logs is that this relates to the clock sync issue between Binance and users local system clock. We still don't really have a solid solution here, it depends on your NTP sync settings and how the Binance server is synced/configured.

I don't believe this has anything to do with requesting historical data, as that has not occurred yet during live node start, at the point you captured those logs.

The messages are simple a _warning_ that the `ts_event` is greater than `ts_init` which shouldn't happen because the time an event occurred _should_ always be prior to the time a data object based on the even is initialized.

**Comment by cjdsellers** [comment]
Closing as this was just a warning, and a known Binance server clock sync issue.
