### ISSUE TITLE
Logger `register_sink`

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#1025]
Hi,
This is more of question, I see `register_sink` is no longer available in this https://github.com/nautechsystems/nautilus_trader/commit/6a9cb7cc submission. How the same can be achieved now? I was using for saving logs to file and CloudWatch.

**Comment by cjdsellers** [comment]
Hi @rsmb7z 

We think it's good idea to push log sinks outside the scope of Nautilus, since there are so many different types, and configurations. For instance something like [vector](https://vector.dev/) could handle your [CloudWatch sink](https://vector.dev/docs/reference/configuration/sinks/aws_cloudwatch_logs/).

I understand there's extra overhead for you here because you already had it running. Our goal is to dismantle the Cython as fast as possible though, what do you think?

**Comment by rsmb7z** [comment]
> I understand there's extra overhead for you here because you already had it running. 

Setup differently is not a problem at this stage. I see that there is option to write to file in `nautilus_logger = Logger(clock=LiveClock(), level_stdout=LogLevel.DEBUG, file_path=file_path)`, and it works as well. However couldn't find how to pass path through TradingNode, if you can provide some clue please?

> I understand there's extra overhead for you here because you already had it running. Our goal is to dismantle the Cython as fast as possible though, what do you think?

Yes, apart from performance at least better debug tools. I have already starting learning on Rust so ready to fly with :smiley:

> We think it's good idea to push log sinks outside the scope of Nautilus, since there are so many different types, and configurations. For instance something like [vector](https://vector.dev/) could handle your [CloudWatch sink](https://vector.dev/docs/reference/configuration/sinks/aws_cloudwatch_logs/).

Sounds perfect, so we can push logs from file to CloudWatch.

**Comment by cjdsellers** [comment]
You'll find that option in the `TradingNodeConfig`, amongst these:

```python
    log_level: str = "INFO"
    log_level_file: str = "DEBUG"
    log_file_path: Optional[str] = None  # <-- this one
    log_rate_limit: int = 100_000
    bypass_logging: bool = False
```

**Comment by cjdsellers** [comment]
It sounds like we're on the same page, so closing this 😄
