### ISSUE TITLE
Books and Ladders, Deltas etc should use Price and Quantity

### ISSUE THREAD

**Issue by micapumono** [nautechsystems/nautilus_trader#1071]
# Feature Request

For efficiency and standardisation we should use the internal efficient numeric types instead of floats all the way from info to execution.

**Comment by cjdsellers** [comment]
Hi @micapumono 

I definitely agree that floats aren't a good choice, even if performant they are not good for comparisons.

In terms of efficiency it probably wouldn't be a good approach to initialize millions of price and quantity Python objects, which may never actually end up being used for any book operations, even with some object pool pattern. Dropping down into Cython, things might get more efficient with assigning directly to the backing struct in C with the `from_raw_c` type functions.

The intent is to revisit this with the Rust order book, where we might have the potential of using structs there, although many high performance order books I've seen just use fixed precision ints (like the raw values we use for the value objects).

If you did want to refactor the current Cython order book to use `Price` and `Quantity` over floats, using the `from_raw_c` functions to initialize, then I would support this effort and would happily take any PR, even if performance would drop a little.

Otherwise the plan is to revisit this when looking at the Rust `OrderBook` and `MatchingEngine` impls, which will happen after the domain model is ported (currently in progress).

It will of course be much better than the skeleton which currently exists
https://github.com/nautechsystems/nautilus_trader/tree/master/nautilus_core/model/src/orderbook

**Comment by cjdsellers** [comment]
Now implemented with the new core order book, we're using the core `Price` and `Quantity` types internal to the book and so all float comparisons there have been removed.
