### ISSUE TITLE
``Actor`` cannot handle historical data if requested in `on_start` method

### ISSUE THREAD

**Issue by miller-moore** [nautechsystems/nautilus_trader#1102]
# Bug Report

From nautilus_trader/common/actor.pyx, it appears that `on_historical_data` is only called when the actor's `fsm` state is `RUNNING`:
![image](https://github.com/nautechsystems/nautilus_trader/assets/8103681/0dce438c-3d81-41df-b32f-924ca2a4e810)

The actor's `fsm` state is `INITIALIZED` until the actor's `on_start` method completes. Therefore, if users request historical data in `on_start`, the `on_historical_data` method is never called. 

### Expected Behavior
That `on_historical_data` is called when requesting historical data in the `on_start` method (as shown by several nautilus_trader example strategies, e.g., `request_bars`).

### Actual Behavior
`on_historical_data` cannot be called based on the condition that `fsm.state == ComponentState.RUNNING`

### Steps to Reproduce the Problem

1. Subclass the EMACross strategy, implement `on_historical_data`, and log whatever is received (which was nothing in my test)

### Specifications

- OS platform: macOS 13.3.1
- Python version: 3.10.8
- `nautilus_trader` version: 1.173.0

**Comment by cjdsellers** [comment]
Hi @miller-moore 

It seems this was on oversight on my part, the `handle_historical_data` method was copied over from the other handlers, where the intent is these would only be called when the strategy state is running (i.e. for any reason the strategy may be in a `STOPPED` state while a system/node is running, and so it's not expected the strategy would still react to the arrival of _real-time_ data). 

Given requesting historical data would be very common in the `on_start` as per your use case, I've removed the condition which requires the strategy to be running to call `on_historical_data`.

So this should now work as per the expected behavior you listed above.

Note the backtest and live examples are successfully hydrating registered indicators, because this is done prior to the `handle_historical_data` call, where that FSM condition check occurs.

Pushed to `develop` branch now.
