### ISSUE TITLE
Nautilus panics if trader_id doesn't have the correct format

### ISSUE THREAD

**Issue by imcu** [nautechsystems/nautilus_trader#1128]
# Bug Report
Nautilus panics if `BacktestEngine` trader_id param doesn't have the correct format.

### Expected Behavior
Nautilus should accept any string as a `trader_id`. It only accepts $STRING-$NUMBER now and this is not documented in the method `BacktestEngineConfig` constructor docstring.

### Actual Behavior
Nautilus panics if trader_id doesn't have the correct format

### Steps to Reproduce the Problem

1. Create a BacktestEngine with "BACKTESTER" as the trader_id parameter in the config.

### Specifications

- OS platform: MacOSX
- Python version: python 3.11.3
- `nautilus_trader` version: latest develop

**Comment by cjdsellers** [comment]
Hi @imcu 

Thanks for the report here. I think you've uncovered an issue with the general approach to the Python/Cython API into Rust, generally Rust should not be panicking from an input arriving from Python, and everything should be validated at that layer with Python exceptions raised where necessary. Many condition checks were removed in the name of performance, but taking some cursory measurements I don't think this was worth the clunkiness of finding out about an invalid ID through a Rust panic.

I've added the condition checks (in Cython) for all identifiers back in, which will raise a Python `ValueError` when they fail.

As for why the trader ID needs a hyphen, the second component of the ID represents a unique numerical tag which can be used for order and position IDs, so that the nodes IDs don't collide with those from another node (say for identical timestamps and strategy IDs), this is necessary for larger distributed systems. We could get away with trader IDs being anything, within a single node, but then this would be harder to manage later in a larger system, so we opt for stricter requirements from the outset.

This is actually documented already, but these docs could be improved. Especially where primitive strings are being parsed into IDs with strict requirements for hyphens (the config objects have very sparse docs right now).

From the docs:
https://docs.nautilustrader.io/develop/api_reference/config.html#nautilus_trader.config.backtest.BacktestEngineConfig

```
trader_id ( str ) – The trader ID for the node (must be a name and ID tag separated by a hyphen). 
```

Closing this as the fix / better Python exceptions has been pushed to `develop`, with docs pending. Many thanks again!
