### ISSUE TITLE
Reloaded backtest does not execute orders loaded from cache database

### ISSUE THREAD

**Issue by imcu** [nautechsystems/nautilus_trader#1130]
# Bug Report
I am trying to test the following behaviour:
1. Run nautilus with a small backtest where there is one Long position that takes profit. There are a total of 3 orders in a bracket: entry - limit/tp - limit/sl stop market
2. Configure nautilus with a Redis cache database
3. Run the entire backtest once to make sure execution is as expected. The result is that the position is closed in profit through the TP limit order.
4. Run the backtest until the time index after the entry order is executed and the long position is opened and throw exception to interrupt execution
5. Run the backtest again, starting from the time index where we threw the exception in step 4.

### Expected Behavior
The long position should be closed in profit

### Actual Behavior
The long position remains open and no order is executed in step 5. described above

### Specifications

- OS platform: osx
- Python version: 3.11.3
- `nautilus_trader` version: 1.175.0 (build from latest develop)

**Comment by cjdsellers** [comment]
Hi @imcu 

So two changes went in yesterday which should address this issue:

- All common start logic has been pushed down to the `NautilusKernel` and so will be the same for backtest and live (with some difference depending on whether there's an event loop available which is not applicable for backtests).

- Then specifically your issue above should be fixed with [this change](https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/cache/cache.pyx#L243) which has been pushed to `develop` branch.

Closing this for now and please report back if any further issues! :pray:
