### ISSUE TITLE
Error in Quantity.from_str

### ISSUE THREAD

**Issue by Tzumx** [nautechsystems/nautilus_trader#1174]
# Bug Report
Working with historical data, I've noticed that when trying to get hour bars for `LINAUSDT` I get an exception., 
`ValueError('invalid "value" greater than "QUANTITY_MAX" 18_446_744_073.0, was 19_495_898_213.0')`
As i understand problem is in method `Quantity.from_str` in `parse_to_binance_bar` which crashes when trying to parse kline data to bar, like:
`Quantity.from_str('19495898213')`

### Expected Behavior
Parse kline data to bar without mistakes

### Actual Behavior
Crash while parsing historical data for `LINAUSDT` in `Quantity.from_str`.

### Steps to Reproduce the Problem

1. Request historical `LINAUSDT-PERP.BINANCE-1-HOUR-LAST-EXTERNAL`  bars
2. Got the error.

### Specifications

- OS platform: Ubuntu 22.04
- Python version: 3.11
- `nautilus_trader` version: 1.175.0

**Comment by cjdsellers** [comment]
Hi @Tzumx

Sorry to see you running into this issue.

I'll direct you to this previous discussion, where the reasoning behind the design choices are briefly explained.
https://github.com/nautechsystems/nautilus_trader/issues/1019#issuecomment-1438125859

As per the error message you describe, the value types `Price`, `Quantity` and `Money` are backed by 64-bit integers for efficiency. We could extend the range to 128-bits, but then this would double the memory footprint for all of these types.

There are many trade-offs necessary to reach the performance goals for the platform, so in this case we elected to constrain the values which Python could otherwise represent natively, because the cost to support larger values is too high relative to a few use cases where extremely large values > ~18.4 billion are required.

As per the comments from #1019 we could get around this issue by implementing some `BigBar` data type, and I'd be happy to support and guide any PR you wanted to make along these lines.

Please let me know your thoughts on this, however closing this for now as there is no bug here, but a design limitation.
