### ISSUE TITLE
Feature Request: Automated Generation of Stub Files for Cython Modules in `nautilus_trader`

### ISSUE THREAD

**Issue by kivo360** [nautechsystems/nautilus_trader#1405]
# Feature Request

Nautilus Trader, known for its high-performance trading infrastructure, utilizes Cython for critical parts of its codebase. Cython, blending Python and C, offers performance benefits but lacks in providing stub (.pyi) files necessary for enhanced type checking and IDE features like code completion.

These stub files can be generated though the build process and dynamically using mypy's [stubgen](https://mypy.readthedocs.io/en/stable/stubgen.html) library. An example of a build process to create stubs (.ipy) files is [cythonbuilder](https://github.com/mike-huls/cythonbuilder). 

If I had the immediate bandwidth to do it I would. This would be super convenient to have for everyone.

**Comment by cjdsellers** [comment]
Hi @kivo360

Thanks for the suggestion here.

I have a quick play with `stubgen`, and it does look promising, although I ran this fairly vanilla command:
```
stubgen -p nautilus_trader

Processed 430 modules
Generated files under out/nautilus_trader/
```

It then resulted in this on the pre-commit:
```
Found 350 errors in 152 files (checked 676 source files)
```

So it looks promising, but appears to need some tweaking:
- We only need to generate `.pyi` files for the C extension module dynamic libs (I think?)
- It should be integrated with the `build.py` build and happen automatically, like the way `cbindgen` is setup with the Rust core

If the above can be done and results in no mypy errors, and working type stubs, then we'd be happy to incorporate it into the codebase - as its recognized this would be very helpful for users and contributors.

Otherwise, I have to invest my own time into other areas, as a more ultimate goal is to port to Rust with pyo3, and we already have a growing `.pyi` file for that.

**Comment by kivo360** [comment]
I'd say keep focusing on porting to Rust. I generated some typings as well and ran into the same issue. 

I don't believe the problem can be fully solved using cython builds. I think it'll be a much better time if the code kept progressing. I'm currently trying simple strategies, exploring data management techniques (to handle more complex backtests)

If I have the bandwidth to contribute to the project in the future I will.

**Comment by woung717** [comment]
@cjdsellers G'day, I managed to generate .pyi stub files from .pyx files using the [cythonbuilder](https://github.com/mike-huls/cythonbuilder) project, after making tiny edits to the code. There are more files that need to be checked, but these seem like low-hanging fruit for now.

I know porting to Rust is ongoing at the moment. Can I submit a pull request with the added pyi files? Is there any possibility of changing the current pxy files (interfaces) further? 

Thanks!

<details>
<summary>Background</summary>

I am currently developing a [VS Code plugin](https://github.com/woung717/backtest-manager-vscode) for backtesting. It currently supports Backtrader and VectorBT, and I am considering adding Nautilus Trader too. However, I found that VS Code's Pylance/Pyright cannot recognize Cython code, which makes writing code with Nautilus Trader in VS Code without IntelliSense support quite a pain. I hope that porting to Rust soon is the best, but I think it would be good to have an intermediate solution.

</details>
