### ISSUE TITLE
Portfolio Allocation Tutorial

### ISSUE THREAD

**Issue by kivo360** [nautechsystems/nautilus_trader#1410]
# Feature Request: Portfolio Allocation

I'm not sure how to do things like bring price information from multiple instruments into a single place so I can do an aggregate calculation. It seems as though there's only a single instrument per strategy. How do I pull multiple pieces of information to make a decision?

However, to do portfolio allocation, one needs to group various price information into a single dataframe [(like here)](https://pyportfolioopt.readthedocs.io/en/latest/UserGuide.html#processing-historical-prices) to do the calculations. The calculations are ungodly slow, and likely need to be done in the background anyway. Even so, this is something I'm still curious about regarding this framework.

**Comment by kivo360** [comment]
I've thought about it, I just need to ensure multiple assets are run on and access within a single backtest. The backtest just needs to have a reference ID, and I would just need to sync the clock's timestamp value.

I could just send commands to an external service responsible for taking all of the data and producing a desired portfolio allocation. I could could pull the results in a MVCC like manner for my algorithms.

1. So I really just need to run multiple assets at the exact same time.
2. Synchronize the clock using some real-time API or something.

**Comment by cjdsellers** [comment]
Hey @kivo360 

> It seems as though there's only a single instrument per strategy

Actually, a strategy can have as many instruments as you have resources.

> The calculations are ungodly slow, and likely need to be done in the background anyway. Even so, this is something I'm still curious about regarding this framework.

Checkout the `Executor` class thats available for all actors (and strategies).

It sounds like that solution is probably a little more complex than what you need, if all you're doing is shipping off compute and synchronizing the results.

Nautilus is pretty high overhead to learn, and we're playing catch up with the docs, but if you stick with it you'll find many of the tools you need already exist for the above.

Closing this just because there's no clear actionable at this stage, feel free to continue with questions in the Discussions section, or even on Discord.
