### ISSUE TITLE
Cash account allows short selling during backtest

### ISSUE THREAD

**Issue by Troubladore** [nautechsystems/nautilus_trader#1510]
# Bug Report
This may be by design, but when configuring a backtest with a venue that uses
```
 engine.add_venue(
    venue=Venue("XNAS"),
    oms_type=OmsType.NETTING,
    account_type=AccountType.CASH
    ...
```
, I do not expect short selling to occur.

In the attached file, there are several instances of short sales, one example is:
2022-08-10T20:30:00.000000000Z [INF] BACKTESTER-1.Portfolio: QQQ.XNAS net_position=-100

### Expected Behavior
Attempts to submit short sell orders within a CASH account should be rejected by the engine.

### Actual Behavior
Short sells are submitted and filled.

### Specifications
See attached log file for details.
[Cash_Netting_Reduce_Only_False_No_Bet_Sizing.txt](https://github.com/nautechsystems/nautilus_trader/files/14367136/Cash_Netting_Reduce_Only_False_No_Bet_Sizing.txt)

**Comment by cjdsellers** [comment]
Hey @Troubladore

Thanks for the report here and good catch.

I believe this bug is actually solved on latest develop branch [here](https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/backtest/matching_engine.pyx#L684), although specific to equities on cash accounts. Let me know if you'd consider different logic here?

We're due to release at the end of the week, now that Windows GitHub runners are behaving themselves again.

Closing this for now, thanks for your patience! :pray:
