### ISSUE TITLE
logging: Error sending log event: is printed when logging messages if the logger is manually created

### ISSUE THREAD

**Issue by davidsblom** [nautechsystems/nautilus_trader#1558]
# Bug Report

logging: Error sending log event: is printed when logging messages if the logger is manually created

### Expected Behavior
Logging messages are printed to stdout with timestamp information without errors in the printed strings

### Actual Behavior
Every logging message is printed with `Error sending log event: ` in front of the message without showing the time stamp 

### Steps to Reproduce the Problem

1. Before calling any functions from NT, initialize the logging system with:
```
init_logging(
        level_stdout=LogLevel.WARNING,
        print_config=True,
    )
logger = Logger(__name__)
```
2. Run a backtest. All log messages have the `Error sending log event: ` prepended to it and do not show the timestamp.

### Specifications

- OS platform: OS X
- Python version: 3.10.12
- `nautilus_trader` version: 1.190.0

**Comment by davidsblom** [comment]
Please note that if `init_logging()` is not called before the backtest, the logging messages are printed without any errors.

**Comment by davidsblom** [comment]
Also good to add that this issue is introduced in 1.190. In 1.189 this issue is not there.

**Comment by davidsblom** [comment]
Just noticed that the problem also occurs when running multiple backtests in a row. The first backtest is fine, the next ones have the same errors with logging. With my setup, the engine is created at the start of the start of the test and completely disposed at the end.

**Comment by cjdsellers** [comment]
Hi @davidsblom

Thanks for the detailed report.

The issue we have here is the introduction of the `LogGuard` which is returned when initializing the global logging system. When this guard is finally deallocated and garbage collected by Python, it will shut down the logging system - ensuring that all log messages are flushed and the `logging` thread which would be ending - is joined.

Try and assign the `LogGuard` returned from the `init_logging` function somewhere so that it will be kept alive for the duration of the multiple backtest runs. When I tried the below snippet at the top of one of the backtest examples, it ran as expected (without assigning the guard I saw the same error as you):

```python
    guard = init_logging(
        level_stdout=LogLevel.INFO,
        print_config=True,
    )
    logger = Logger(__name__)
    logger.info("Some event before kernel built")
```

I think this is a consequence of initializing the logging system outside of the `NautilusKernel` object.

Let me know how you go with this on the multiple backtest runs, we may need to make a further change to `BacktestNode` to make sure the initial log guard is kept alive.

**Comment by cjdsellers** [comment]
I checked the `BacktestNode` code, and it looks like we hold a reference to all of the engines anyway, which will hold a reference to the initial `LogGuard` and keep it alive. I've gone ahead and improved how we manage this reference, and exposed some methods to be able to access it.

**Comment by davidsblom** [comment]
Initializing the logging system outside of NT works when holding a reference to the LogGuard. Also works great also for multiple backtests.
