### ISSUE TITLE
Implementation tardis.dev for backtest and LOB data

### ISSUE THREAD

**Issue by jpmediadev** [nautechsystems/nautilus_trader#162]
Awesome project! Thanks for open source.

Please specify better way to implement this, to maintain a clean project organization

https://docs.tardis.dev/api/tardis-machine

**Comment by cjdsellers** [comment]
This could be a good solution for sourcing data. I'll have a closer look at the docs and if there are any other options. 

At the very least I can imagine we could support the data format for ease of ingest.

**Comment by cjdsellers** [comment]
What is your goal?

You're wanting to use CSV data downloaded from tardis for backtesting?

A C-level order book will be implemented into the platform over the next few weeks.

**Comment by jpmediadev** [comment]
> A C-level order book will be implemented into the platform over the next few weeks.

Great news!

They have Tardis Machine Server(https://docs.tardis.dev/api/tardis-machine)
it is very convenient to use for a backtest close to reality

no need to fiddle with files, you can just specify the periods of history and it emulates streaming data including LOB
processing a large amount of LOB CSV files requires memory and CPU overhead, and they somehow need to be glued together to emulate a continuous process

**Comment by cjdsellers** [comment]
I've looked at the docs more closely. I see that you connect to their API as you would a live exchange however they can replay you historical data based on your requests.

To support this we'd need a new `tardis` adapter which implements both the `LiveDataClient` and `LiveExecutionClient`. There may even need to be a central client which accepts the data and sends to both of the above clients, this is so data is available inside the execution client to simulate order fills etc similar to the `SimulatedExchange`.

This is my initial intuition, it's definitely an interesting use case.

Right now there is some heavy development work on the core platform to support order book requests and streams, and build out the initial live adapters. So at this stage I can't begin implementing anything like this. 

I can however support your efforts if you'd like to give it a try - you could make work in progress pull requests so that I can see your code progress and comment.

Please follow the pattern in the other integration tests by having a `_sandbox.py` which can run scripts to save responses in JSON format which can then be used to mock the tardis API (we don't want to make calls to the real tardis API in the tests).

You'd also want to add a `tardis_test_node.py` to the live examples to help with dev and also demo the capability.

What are your own thoughts on this?

**Comment by cjdsellers** [comment]
Further to the above, I may have misunderstood what tardis is actually providing. Rather than a 'live replay' its just providing historical data over rest or websockets? so that one don't have to string together and maintain CSVs, as you say.

In this case it's much simpler to write a simple `DataProvider` type class which just requests the appropriate data you need and gets it into a pandas DataFrame in the correct format for a backtest engine.

I'm also willing to reconsider the data format for the backtest engine and/or make it more configurable.

Order book support still under development, but it's right at the top of the backlog.

**Comment by jpmediadev** [comment]
yes, they provide only L2 historical data without Execution + Tardis Machine allows to seamlessly switch from backtests to real websocket feed locally standalone hosted, it all works pretty fast (typescript, cache, parallel) 
of course all this functionality can be implemented independently -  only uses CSVs file requests and adaptation to the current implementation of DataProvider (solving problems for loading and storing large L2  Pandas CSV in the memory and also need memory to processing this data for ML models) this will increase the complexity....

Now i think that these 2 processes should be separated - good idea to use BlackBox a strategy  to transmit only signals and tick data for backtest

**Comment by jpmediadev** [comment]
add support for Tardis.dev [quote, trade] CSV file format
 https://github.com/nautechsystems/nautilus_trader/pull/168/commits/2e2f6245a42337ad5f8a398e68c7678579769150
but something went wrong ...

**Comment by cjdsellers** [comment]
Merged changes
