### ISSUE TITLE
make install-debug is not working

### ISSUE THREAD

**Issue by faysou** [nautechsystems/nautilus_trader#1715]
# Bug Report

### Expected Behavior
should compile without problem

### Actual Behavior
I get the following error

 make install-debug
BUILD_MODE=debug poetry install --with dev,test --all-extras --sync
Installing dependencies from lock file
Path /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a17a7759g2/croot/anyio_1706220182417/work for anyio does not exist

Path /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a17a7759g2/croot/anyio_1706220182417/work for anyio does not exist
make: *** [install-debug] Error 1

### Steps to Reproduce the Problem

1. run make install-debug

### Specifications

- OS platform: macos
- Python version: 3.12.4
- `nautilus_trader` version: develop branch

**Comment by cjdsellers** [comment]
Hi @faysou

My first impression is this is a local issue, since `anyio` is not a required dependency and this command is working locally for me and in CI. 

Also note that `--sync` is going to uninstall any package which is not a dependency specified in the `pyproject.toml` (this is done to make sure we have a clean environment when developing - which tends to be when this command is used).

Did you modify the source code at all? I would recommend you try a new poetry environment and also clear it's package cache.

Hope that helps!

**Comment by faysou** [comment]
Thank you for your reply @cjdsellers  I managed to install the debug version when not using --sync. The problem was likely that other packages are installed in the environment and that dependencies can't be uninstalled without problems.
