### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#175]
Builds for `windows-latest` (Windows Server 2019) are failing for very low level reasons e.g.

```
 build/optimized\nautilus_trader\core\message.c(1402): error C2061: syntax error: identifier '__uint128_t'
```

Which is a c typedef for a 128 bit unsigned integer in the UUID type.

See more details here;
a9e99df623c1830caa593188210754eb0c00c2c8

I'm fielding these questions to the community
* How valuable is Windows support?
* Is anyone currently running a trading system in production, or backtest/research on Windows?

Also, if anyone with knowledge has ideas on how to approach fixing the build errors - I'm open to suggestions.
Redis support on Windows is also a potential issue.

**Comment by ian-wazowski** [comment]
I solved various problems when applying nautilus_trader to windows. It was not easy(There are serious maintenence problems I don't recommand make nautilus_trader supports windows, very time consuming).

1. How valuable is Windows support? No
2. Is anyone currently running a trading system in production, or backtest/research on Windows? Me

**Comment by cjdsellers** [comment]
Out of interest, could you please provide some more details of what problems you managed to fix?

Also, I don't think `uvloop` works for Windows - which isn't a show stopper, it would just use vanilla `asyncio` with lower performance.

**Comment by ian-wazowski** [comment]
First of all, I used Windows 10 32bits. The reason is that my country's broker allows access only when using 32bits Windows (due to a security program. I don't know the details).

1. The UUID generator issue you mentioned became a problem. In windows 10 32bits, UUID4 could not be expressed(because it is using 128bits), so the UUID4 source code was modified to 64bits(uint) (the longest length that can be expressed in windows10 32bits).

2. There is a compiler problem. To compile cython, you need to install mingw or visual studio. If you do not use the version that cython asks to install, the compilation will not work. (The installation size seems to be at least 3 gb.)

3. Since ThreadExcutor has overhead, all of them have been changed to queues that operate in a single thread.

4. There are a few more big changes, but this has changed because it is related to a Korean broker. (It was an environment where asyncio could not be used, all asyncio codes were changed)

For me, at least I don't know how to make nautilus trader supports windows 10 at the level that keeps the productivity now.

**Comment by cjdsellers** [comment]
Thank you for the info - very interesting.

I think it wouldn't make sense to attempt to change the UUID to support a 32-bit platform, also a 64-bit integer also wouldn't meet UUID version 4 specs.

I agree with you it would be very expensive to somehow maneuver to support Windows and then maintain it. Also, Ubuntu is becoming increasingly easy to run on top of Windows.

However, let me know if there are easy changes I can make which support your efforts to run with your current setup (such as that `psutil` fix).

Closing this for now unless anyone wants to revive the Windows support discussion.
