### ISSUE TITLE
About formatter

### ISSUE THREAD

**Issue by sunlei** [nautechsystems/nautilus_trader#2103]
I’ve noticed that both `black` and `ruff` are being used as formatters in the current project, and their settings are also different, with `line_length` set to `100` for black and `150` for ruff.

Both are being used in the `pre-commit` configuration as well. Should we consider removing `black`?

**Comment by cjdsellers** [comment]
Hi @sunlei

`black` and `ruff` can actually be used together and compliment each other. As far as I'm aware, `black` is still a more capable formatter than `ruff` (which is _mostly_ known as a linter, but can format).

About the line length config difference:
```
line-length = 150  # Reduce to 100
```

This is just for lint rule E501, if you reduce that to 100 you'll see the following output (mostly throughout the test suite):
```
Found 541 errors (27 fixed, 514 remaining).
```

Which could be solved by either:
- Reducing all of those line lengths
- Or, adding a `# noqa: E501` beside each one

Both of which is high effort for low reward, which is why it hasn't been done at this point.

I'd consider removing `black` if `ruffs` formatting capabilities have vastly increased recently, otherwise as above they compliment each other well I think?

Also, we still have to use `isort` because `ruff` doesn't work with Cython for formatting the imports (so `isort` can go along with Cython, eventually).

**Comment by sunlei** [comment]
In our project, we've fully switched to using `ruff` instead of `black`.
Similarly, for the same reason, we’ve kept `isort`, it only applies to `Cython` files.

I encountered a conflict between `black` and `ruff --fix` in a PR yesterday, which is why I’m suggesting we keep only one of them.

**Comment by sunlei** [comment]
The issue occurred in the import-related section. When I ran `make pre-commit`, `black` first modified the code, and then `ruff --fix` made further changes. When running `make pre-commit` again, the process repeated.

As a result, I had to use `fmt: off` to bypass the issue:
https://github.com/nautechsystems/nautilus_trader/pull/2102/commits/44a2657bc763b4b8b65951a6ce20dedc8046bb82

**Comment by cjdsellers** [comment]
It sounds to me like the config in the `pyproject.toml` wasn't being picked up if you're manually invoking those commands alongside pre-commit.

The pre-commit has to be stable for all commits, otherwise any diff will result in a failure.

**Comment by cjdsellers** [comment]
Were there some extra rules or config changes you might want to make to the configs in the `pyproject.toml`?

I regularly run `make pre-commit` during development.

**Comment by sunlei** [comment]
I don't have experience using both `black` and `ruff` simultaneously. In our project, we always choose one or the other.

So, I don't have a particularly good solution for handling this issue at the moment. :)

**Comment by cjdsellers** [comment]
I'll have a closer look at the `ruff` formatting situation, if it can do most or all of what `black` does then I'd be open to removing `black`.

**Comment by sunlei** [comment]
In our project, `ruff` completely replaces `black`, and we have already made the switch.

Just for your reference :)
