### ISSUE TITLE
Consider moving away from pushing to `master` directly

### ISSUE THREAD

**Issue by smallstepman** [nautechsystems/nautilus_trader#2140]
I'm having a hard time making sense of what's going on when there are so many commits with little granular changes
<img width="669" alt="image" src="https://github.com/user-attachments/assets/ff7d0974-fab4-4c30-9acc-2514329dc11e" />

I can appreciate it can be hard to 'bundle up' small code changes, however for stuff like CI or doc updates, it should be quite easy to do.
if https://www.conventionalcommits.org/en/v1.0.0/ would've been followed, the commits history could look like this:
```
docs: update README, installation docs, release notes (#9997)
ci: fix CI builds, update codecov, fix running examples (#9998) 
fix: Revert nanos_since_unix_epoch optimization (#9999) <- PR telling why 
fix: request_aggregated_bars metadata handling (#2137)
feat: upgrade v4-proto for dYdX (#2136)
fix: instrument info retrieval for Bybit (#2134)

**Comment by cjdsellers** [comment]
Hi @smallstepman

Thanks for the suggestion.

I can appreciate how a standard like this may make things easier for people established in these practices, but for now I think this just adds unnecessary ceremony to commit messages. Currently commit messages just need to be imperative voice, clear and not too long.

It's not a small decision to introduce a standard like this when we already have so many commits which didn't adhere to the standard. PR's are squashed, but merges to `master` branch are not to preserve the atomic commit history.

There have been many smaller changes lately with a revamp of the main `build` workflow (most of which actually happened on a separate branch).

> I can appreciate it can be hard to 'bundle up' small code changes, however for stuff like CI or doc updates, it should be quite easy to do.

Exactly, sometimes it is hard to 'bundle up' small changes, or know with foresight exactly what those will be. I'd also be hesitant to introduce a rigid standard which increases the overhead to making small changes and improvements to the codebase, to optimize for the readability of a git log. I think better to optimize for the current faster pace of development, at least for now?

I'm also happy maintaining the release notes in the current way, rather than using something like this to help generate them automatically (which I think can become less human-readable).
