### ISSUE TITLE
Why not use pixi as a package management tool?

### ISSUE THREAD

**Issue by Gwill** [nautechsystems/nautilus_trader#2147]
https://pixi.sh/

Poetry does not manage different versions of Python interpreters well enough.

Pixi looks good. And it is faster.

**Comment by limx0** [comment]
> Poetry does not manage different versions of Python interpreters well enough.

Could you elaborate on this @Gwill? What specifically does poetry not handle with respect to different python versions? I have no issues running multiple versions of python via poetry.

**Comment by rterbush** [comment]
I've not tried pixi but I must say that if there is any consideration for moving from poetry, I would highly recommend that the project look at using `uv`.  From the creators of `ruff`.

https://astral.sh/blog/uv-unified-python-packaging

Best thing to happen to python in decades...

**Comment by faysou** [comment]
https://thenewstack.io/rust-will-explode-sboms-will-be-duds-open-source-predictions

Related. jj seems interesting too.

**Comment by cjdsellers** [comment]
Hi @Gwill

I also haven't had any issues running multiple python versions with poetry. When poetry does have an issue (rarely), it can normally be fixed by clearing its cache or creating a new venv.

@rterbush agreed, and we've had our eye on uv for a while. Most likely will be the one we move to, at the right time.
There was a great [Jane Street talk](https://youtu.be/gSKTfG1GXYQ?si=lOB8BTmSnPXJQBbl) on it recently by Charlie Marsh.
