### ISSUE TITLE
Oanda integration

### ISSUE THREAD

**Issue by cjdsellers** [nautechsystems/nautilus_trader#230]
**The Oanda adapter is currently a work in progress.**

Oanda is a brokerage popular with retail traders https://www.oanda.com. It was chosen as an integration mainly due to the quality of their API, and range of trading products offered.

The `OandaDataClient` has some functionality however the `OandaExecutionClient` hasn't been started as yet.

**Comment by crazy25000** [comment]
@cjdsellers are you able to run the Oanda live example and stream prices/run strategy? I used to be able to, but not anymore.

**Comment by cjdsellers** [comment]
Good find, I actually haven't run it for a while - will look into it today.

This is also something I wanted to complete (the `ExecutionClient` for OANDA). Did you want to help on this one?

**Comment by crazy25000** [comment]
@cjdsellers yes I would love to!

**Comment by cjdsellers** [comment]
So at this stage I feel Oanda isn't the best choice of integration for the project - given that time and resources are limited there are other exchanges/brokers which would suite our direction more.

For example I feel time invested into proper integrations for some of the larger more established crypto exchanges / ECNs and Interactive Brokers would be time better spend. Thoughts?

**Comment by crazy25000** [comment]
@cjdsellers sounds good. Before we even do that, I'd recommend we come up with a generic workflow so that any stream can be accepted regardless of vendor/API. I've been reviewing the current adapters to try and figure that out. 

I can help with IB, I created an account to get access to the API. Wish they had better/modern documentation though.
