### ISSUE TITLE
Illegal characters found in parameter 'newClientOrderId';

### ISSUE THREAD

**Issue by thematz1** [nautechsystems/nautilus_trader#383]
`2021-07-11T19:35:00.733658Z [DBG] BTCUSDT-BINANCE-001.ExecEngine: <--[EVT] OrderRejected(account_id=BINANCE-xxxx@xxxx, client_order_id=O-20210711-193500-BINANCE-001-001-982, reason='binance {"code":-1100,"msg":"Illegal characters found in parameter 'newClientOrderId'; legal range is '^[a-zA-Z0-9-_]{1,36}$'."}', event_id=4e6f2ef6-5d7e-17f8-3098-02c987d7a49f).
2021-07-11T19:35:00.734090Z [DBG] BTCUSDT-BINANCE-001.RedisCacheDatabase: Updated StopMarketOrder(SELL 0.002100 BTC/USDT.BINANCE STOP_MARKET @ 33562.68 GTC, state=REJECTED, client_order_id=O-20210711-193500-BINANCE-001-001-982).
2021-07-11T19:35:00.734119Z [WRN] BTCUSDT-BINANCE-001.EMACrossWithTrailingStop-001: <--[EVT] OrderRejected(account_id=BINANCE-xxxxx@xxxx, client_order_id=O-20210711-193500-BINANCE-001-001-982, reason='binance {"code":-1100,"msg":"Illegal characters found in parameter 'newClientOrderId'; legal range is '^[a-zA-Z0-9-_]{1,36}$'."}', event_id=4e6f2ef6-5d7e-17f8-3098-02c987d7a49f).
2021-07-11T19:35:00.734153Z [DBG] BTCUSDT-BINANCE-001.RiskEngine: <--[EVT] OrderRejected(account_id=BINANCE-xxxx@xxx.com, client_order_id=O-20210711-193500-BINANCE-001-001-982, reason='binance {"code":-1100,"msg":"Illegal characters found in parameter 'newClientOrderId'; legal range is '^[a-zA-Z0-9-_]{1,36}$'."}', event_id=4e6f2ef6-5d7e-17f8-3098-02c987d7a49f).
`

I haven't looked deeply but I hav been getting this log. But I felt the need to report it.  I've replaced my email with xxxx but the rest of the log is copy paste.

**Comment by cjdsellers** [comment]
This is an interesting one, `[a-zA-Z0-9-_]` are the legal chars and the order ID is `O-20210711-193500-BINANCE-001-001-982`. So its not obvious whats causing the error, the characters all seem legal.

From their docs:
```
-1100 ILLEGAL_CHARS

    Illegal characters found in a parameter.
    Illegal characters found in a parameter. %s
    Illegal characters found in parameter %s; legal range is %s.
```
Which doesn't help us too much.

I ran a live example and it worked OK for me. The only thing I can think of at this point is that the order ID is quite long, possibly its hitting the character length limit instead, although I'm unsure if there is one and what it may be.

**Comment by cjdsellers** [comment]
Did you manage to figure it out?

**Comment by thematz1** [comment]
Nothing yet.

**Comment by thematz1** [comment]
I was doing some research while at work at it seems {1,36} indicates the number of times the previous token could be matched leading me to believe the character limit is 36. I’m going to do some further research after work, particularly by copy pasting the order id in regex101.com and the regex from the error message

**Comment by thematz1** [comment]
I have confirmed that the order id is exactly 1 character too long, I will look to fix that.

**Comment by thematz1** [comment]
Im not sure if making the UUID shorter would be the best route. Any suggestions @cjdsellers ?

**Comment by cjdsellers** [comment]
So if you’re creating orders through the standard order factory provided with a strategy, then the `ClientOrderId` is generated from machinery you’ll find in common/generators.pyx. This includes a timestamp, trader_id tag, strategy_id tag plus a nonce count from the factory. This ensures uniqueness across many running strategies and trader instances. 

It looks like you’re include BINANCE in one of your tags which is making it quite a bit longer, I wasn’t aware of the order ID character limit for Binance until this issue was raised - however I feel it’s specific enough to that exchange that we don’t need to change the impl at this point, and if we stick with numerical trader_id and strategy_id tags we should stay far enough way from the limit.

Since you mentioned the UUID, I do have a goal of removing the Nautilus UUID class, and generating a UUID4 string from a C library - which could be 2-4x faster and remove the then redundant code.

Closing this for now as I think we’ve figured it out. Please raise any further issues or discoveries!
