### ISSUE TITLE
Improve GenericData topics on message bus

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#522]
### Background / current behaviour
Currently, any generic data that is published on the message bus is given the topic from the data engine of `f"data.{data.data_type}"` where the `__str__` of `DataType` is `f"<{self.type.__name__}> {self.metadata}"`. 

This leads to `MyType(Data)` being published on the topic `"data.<MyType> {}"` which may be unexpected to some people. You can obviously successfully subscribe via `f"data.{DataType(MyType)}.*"` but this seems quite verbose / error prone. Of course this is an advanced usage of the platform - but that doesn't mean we shouldn't try our best to make it _idiot proof_ :smilecry:

### Thoughts / Proposals
1. Could (or should) we use `f"data.{data.data_type.type.__name__}"` (i.e. topic becomes `data.MyType`)? I don't think this is ideal, if someone is using metadata and wants to subscribe based on that metadata. 
2. Can make the DataType `__str__ better if metadata is empty (removing it) ? 
3. Can we create a custom method specifically for the message bus, something like `data.MyType` for no metadata, `data.MyType{key=a}` with metadata?

`3.` Seems the most reasonable to me - keen to hear others thoughts though. 

Another note - it seems like the message bus only records topics that are subscribed to; I was trying to find for some time what topic my generic data was being published on, but `MessageBus.topics()` only returns subscriptions - this is not so useful if you don't know what you're looking for. I wonder how costly it would be to record all topics that have been published?

**Comment by cjdsellers** [comment]
You've raised some good points and there's definitely room for improvement here.

Firstly, lets improve the `__str__` for `DataType` especially as it's being used with the message bus. I like the idea of only including a metadata part of the string if it exists, otherwise just the type name. If metadata exists then as you suggest `MyType{key_a=a, key_b=b,...}` basically just immediately printing the metadata dict - seems intuitive (without the angle brackets or redundant curly braces when there's no metadata). I'm fairly comfortable with the `__repr__` at this stage. Thoughts?

Lastly, I agree the message bus `topics` method could return all topics which are currently being published to. As we already have `subscriptions` with a convenient `topic` filter param to show topics with active subscribers. Would this be the ideal behavior?

**Comment by cjdsellers** [comment]
One additional thought is that if many data feeds have been subscribed to, then this could create a larger hashmap to lookup when checking for subscribers on publish. Without hard numbers though I can't really consider this a blocker or big problem.

**Comment by cjdsellers** [comment]
So the `publish_data` method now requires a `DataType` to be passed as the first arg, which makes it easier to subscribe to the corresponding data type.

The `DataType` string is now formatted as `type|key1=a|key2=b` etc., which is cleaner and simpler (note unless working with the raw message bus, a user isn't required to know this string formatting convention.

I determined the following methods are actually redundant, as the strategy ID can just form part of a data types `metadata` if it needs to be filtered on:
- `subscribe_strategy_data(...)`.
- `unsubscribe_strategy_data(...)`.
- `publish_strategy_data(...) `.

Pushed to latest `develop`, let me know your thoughts?

I'll tackle the message bus `topics` method behavior change tomorrow.

**Comment by cjdsellers** [comment]
For the `Message Bus`:

I haven't touched the `topics` method behavior at this stage, as I couldn't see a clear way to achieve the ideal behavior without adding an additional hashmap lookup on every publish.

However, for clarity I did change the param name for `subscriptions` and `has_subscribers` from `topic` to `pattern`.

**Comment by limx0** [comment]
Yep this is perfect - thanks @cjdsellers.
