### ISSUE TITLE
Discord link is non functional

### ISSUE THREAD

**Issue by goraj** [nautechsystems/nautilus_trader#564]
Link is not working, maybe there are no public channels on the server?

**Comment by cjdsellers** [comment]
Hi @goraj 

You're correct, the discord badge on the `master` branch (as displayed by default) isn't working.

However, it is working on the `develop` branch if you navigate there. It will be fixed with the next release which is a little behind scheduled as I'm just finishing some reconciliation logic before releasing it into the wild.

**Comment by cjdsellers** [comment]
Link is now repaired on the default README.

https://discord.gg/AUWVs3XaCS
