### ISSUE TITLE
[question] I only have 1m bar, I want use 30m and 1m backtest, how to do that?

### ISSUE THREAD

**Issue by LoveAndFree** [nautechsystems/nautilus_trader#566]
I only have 1m bar, I want use 30m and 1m backtest, how to do that?
Can 30m bar aggregate from 1m bar?

**Comment by cjdsellers** [comment]
Hi @LoveAndFree 

Absolutely the platform can achieve this, basically the steps are:
- Process the bar data into either quote ticks or trade ticks.
- Add the `YOUR_INSTRUMENT.VENUE-1-MINUTE-LAST-INTERNAL` bar type to your strategy.
- Add the `YOUR_INSTRUMENT.VENUE-30-MINUTE-LAST-INTERNAL` bar type to your strategy.

Because the bar type is marked as `INTERNAL`, and if you subscribe to this bar type, the platform will automatically subscribe to the necessary ticks, and internally aggregate the bar.

Let me know if you have any other questions or need some more details!

**Comment by cjdsellers** [comment]
The above also depends on what the price type (e.g. `BID`, `ASK`, `MID`, `LAST`) of bar data you both have, and would like to aggregate. This may be an advanced topic and will be added to the user guide soon.

**Comment by LoveAndFree** [comment]
Thanks!
I only have 1m bar data, don't have tick data. so 30m bar can aggregate from 1m bar ?

**Comment by cjdsellers** [comment]
For example (from `examples/fx_ema_cross_bracket_gbpusd_bars_internal`):

```
    # Setup data
    provider = TestDataProvider()
    wrangler = QuoteTickDataWrangler(instrument=GBPUSD_SIM)
    ticks = wrangler.process_bar_data(
        bid_data=provider.read_csv_bars("fxcm-gbpusd-m1-bid-2012.csv"),
        ask_data=provider.read_csv_bars("fxcm-gbpusd-m1-ask-2012.csv"),
    )
    engine.add_instrument(GBPUSD_SIM)
    engine.add_ticks(ticks)
```

So in this case `BID` and `ASK` bar data is converted into quote ticks (4 OHLC ticks for each bar with a 1 minute granularity). These raw ticks can be aggregated into any time bar >= 1 minute in this case.

**Comment by LoveAndFree** [comment]
I got it, thanks!
I have another question.  Why there is no `isinstance(data, Bar)` to  let exchange match order when 1m bar coming to.
note: data client just only have 1m bar.
<img width="793" alt="image" src="https://user-images.githubusercontent.com/6531797/152901563-cba2947b-8024-4ee1-9854-5c2859ecf818.png">

**Comment by cjdsellers** [comment]
Ah actually that functionality exists on the `develop` branch which should be released some time this week.
