### ISSUE TITLE
Stop_market order should provide  trigger_price  instead of price

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#641]
https://github.com/nautechsystems/nautilus_trader/blob/313d7696992608b41b3804f462d6f7062310adeb/nautilus_trader/examples/strategies/ema_cross_trail.py#L259
https://github.com/nautechsystems/nautilus_trader/blob/313d7696992608b41b3804f462d6f7062310adeb/nautilus_trader/examples/strategies/ema_cross_trail.py#L299
Version: The latest main verion and the latest develop version.

**Comment by cjdsellers** [comment]
Hi @graceyangfan 
Thanks for the heads up!
Unfortunately the trailing stops aren't completely implemented yet. Actually one of the remaining core features which need to be done. I see this strategy is manually managing a trailing stop using `StopMarketOrder`(s) and they do indeed have `trigger_price` rather than `price` so I've fixed that and pushed to `develop`.
