### ISSUE TITLE
Installation failed on MacOS/M1

### ISSUE THREAD

**Issue by day0market** [nautechsystems/nautilus_trader#731]
# Bug Report

### Expected Behavior
`pip install -U nautilus_trader ` execution without errors

### Actual Behavior
`ERROR: Could not build wheels for nautilus_trader, which is required to install pyproject.toml-based projects`

[pip_install_output.txt](https://github.com/nautechsystems/nautilus_trader/files/9366978/pip_install_output.txt)

### Steps to

 Reproduce the Problem

1. pyenv install  3.10-dev
2. create virtualenv from installed 3.10-dev
3. activate viratualenv
4. pip install -U nautilus_trader

### Specifications

- OS platform: MacOS Monterey 12.5
- Python version: 3.10-dev, also checked with 3.8
- `nautilus_trader` version: latest (1.150.0)

**Comment by cjdsellers** [comment]
Thanks for the report!

**Comment by cjdsellers** [comment]
It looks like the failure is caused by a missing Cargo.toml manifest. This was due to an incorrect glob pattern in the `include` section of the `pyproject.toml`.

This has been corrected and tested OK, the sdist now including the Cargo.toml, Cargo.lock, README.md and LICENSE under `nautilus_core`.

So you should be able to install from source via the `develop` branch (with Rust installed):
```
pip install -U git+https://github.com/nautechsystems/nautilus_trader#develop
```

We'll also soon be including wheels for macOS and Linux aarch64 / ARM64 so this will become even easier.

I'll consider a special release to correct this around Monday and will leave the issue open until then.

**Comment by cjdsellers** [comment]
This now appears to be working from the `1.151.0` release.

Just tested `pip install -U nautilus_trader` on my MacBook M1 and it works.

```
Successfully built nautilus_trader
Installing collected packages: nautilus_trader
Successfully installed nautilus_trader-1.151.0
```

**Comment by day0market** [comment]
It works for me as well. Thanks!
